worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    types {
        application/javascript js;
        text/plain pde;
    }

    server {
        listen 80;
        server_name localhost;

        root /var/concentration/html;
        index index.html;

        location /code/ {
            alias /var/concentration/html/code/;
	    autoindex on;
        }

        location /cheat {
            alias /var/concentration/html/;
            index cheat.html;
        }

        location ~* \.(js|pde)$ {
            default_type application/javascript;
        }
    }
}
